name: Deploy
on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_publish:
    uses: ./.github/workflows/build_push.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  Deploy:
    needs: [ build_publish ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
